
GET http://localhost:5000/contacts

###

GET http://localhost:5000/contacts/method/email


###
GET http://localhost:5000/contacts/655bd8bae9e607d5a244f43a



###
DELETE http://localhost:5000/contacts/656481b30741344b05671ad0


###
POST http://localhost:5000/contacts
Content-Type: application/json

{
    "name": "Arnie",
    "email": "strongarnie@peteandpete.com",
    "phone": 5558889998,
    "preferredMethod": "email"
}


###
POST http://localhost:5000/contacts
Content-Type: application/json


{
    "name": "",
    "email": "",
    "phone":
    "preferredMethod": ""
}



###
PATCH  http://localhost:5000/contacts/655bd91698525bc0441c9786
Content-Type: application/json

{
    "name": "Benjahmin Lakin Koenigsberg",
    "email": "mrman@gmail.com",
    "phone": 9713765653,
    "preferredMethod": "phone"
}
