GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/15

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Your cousin",
    "subscribedToChannel": "Basil B Vegan"
}

###
DELETE  http://localhost:3000/subscribers/65562f053abbff1a0f9cb503


###

PATCH http://localhost:3000/subscribers/hjhjhjhj
Content-Type: application/json

{
    "name": "Benjahmin Lakin K.",
    "subscribedToChannel": "Basil B Vegan"
}
